In [1]:
A=(1,2,3.5,4,'Edurka!')
print(A)

(1, 2, 3.5, 4, 'Edurka!')


In [2]:
A=[1,2,5.6,8,'Edureka!']
print(A)

[1, 2, 5.6, 8, 'Edureka!']


In [3]:
A={'Age': 33, 'Height' :5.7, 'Occuption': 'Private Employe'}
print(A)

{'Age': 33, 'Height': 5.7, 'Occuption': 'Private Employe'}


In [4]:
A={1,2,3,4}
print(A)

{1, 2, 3, 4}


In [6]:
A={4,4,4}
print(A)

{4}


In [5]:
list=["Hadoop","Python","Android"]
list[1]="Java"
print(list)
del(list[2])
print(list)

['Hadoop', 'Java', 'Android']
['Hadoop', 'Java']


In [8]:
list=["Hadoop","Python","Android"]
list[1]="Java"
print(list)
del list[2]
print(list)

['Hadoop', 'Java', 'Android']
['Hadoop', 'Java']


In [9]:
list=[1,2,3,4,5,'a','b','c']
print(list.pop(3))
list.remove('a')
print(list)

4
[1, 2, 3, 5, 'b', 'c']


In [10]:
list=[1,2,3,4,5,'a','b','c']
print(list.pop(3))
list.remove('a')
print(list)

4
[1, 2, 3, 5, 'b', 'c']


In [11]:
list3=[1,2,5,'Python','Hadoop']
print(type(list3))

print([x**2 for x in [1,2,3,4,5]])

<class 'list'>
[1, 4, 9, 16, 25]


In [12]:
list3=[1,2,5,"Python","Hadoop"]
print(type(list3))
print([x**2 for x in [1,2,3,4,5]])

<class 'list'>
[1, 4, 9, 16, 25]


In [2]:
import numpy as np

In [4]:
multi_array=np.array([(4,1),(2,5),(8,9)])
print(multi_array.sum(axis=0))

[14 15]


In [5]:
multi_array=np.array([(4,1),(2,5),(8,9)])
print(multi_array.sum(axis=1))

[ 5  7 17]


In [6]:
multi_array=np.array([(4,1),(2,5),(8,9)])
print(multi_array.sum(axis=1))

[ 5  7 17]


In [8]:
multi_array=np.array([|(0,1,2,3,4,5),(10,11,12,13,14,15),(20,21,22,23,24,25),(30,31,32,33,34,35),(40,41,42,43,44,45),(50,51,52,53,54,55)])
multi_array[2::2,::2]
print(multi_array)

SyntaxError: invalid syntax (<ipython-input-8-c8c5f1a13a4e>, line 1)

In [10]:
a=np.linspace(1,4,20)
print(a)

[1.         1.15789474 1.31578947 1.47368421 1.63157895 1.78947368
 1.94736842 2.10526316 2.26315789 2.42105263 2.57894737 2.73684211
 2.89473684 3.05263158 3.21052632 3.36842105 3.52631579 3.68421053
 3.84210526 4.        ]


In [11]:
a=np.random.randn(3,4)
print(a)

[[-1.11662755 -1.81597343 -0.76896296  0.61147361]
 [ 0.89356366 -0.29344498 -0.87571479  0.60288676]
 [-1.31145979  0.07996326  0.93583135 -0.27099989]]


In [12]:
a=np.random.rand(3,2)
print(a)

[[0.14754644 0.45737626]
 [0.41709082 0.80583983]
 [0.93713684 0.52051555]]


In [13]:
multi_array=np.ravel([(4,1),(2,5),(8,9)])
print(multi_array)

[4 1 2 5 8 9]


In [15]:
multi_array=np.array([(4,1,2),(5,8,9)])
print(np.max(multi_array))
print(np.min(multi_array))

9
1


In [16]:
import pandas as pd


In [19]:
series=pd.Series([14,23,8,9,10],index=['A','B','C','D','E'])
print(series)

A    14
B    23
C     8
D     9
E    10
dtype: int64


In [25]:
dataframe_records=pd.DataFrame({'Id':[12,13,14,15,16],
                               'Monthly Fee':[2895,2765,np.nan,2800,2895],
                               'Name':['James','Joohn','Irene','Abdul','Nizam'],
                               'Overall Percentage':[86,75,78,90,82],
                               'Transport':[1,1,0,1,1],
                               'Sports':[np.nan,'BasketBall',np.nan,'Cricket',np.nan]})
print(dataframe_records)


   Id  Monthly Fee   Name  Overall Percentage  Transport      Sports
0  12       2895.0  James                  86          1         NaN
1  13       2765.0  Joohn                  75          1  BasketBall
2  14          NaN  Irene                  78          0         NaN
3  15       2800.0  Abdul                  90          1     Cricket
4  16       2895.0  Nizam                  82          1         NaN


In [28]:
dataframe_records=pd.DataFrame({'Id':[12,13,14,15,16],
                               'Monthly Fee':[2895,2765,np.nan,3105,2800],
                               'Name':['Nizam','Farooq','salman','Ganesh'],
                               'Overall Percentage':[86,75,82,90,91]})

print(dataframe_records)

ValueError: arrays must all be same length

In [29]:
series1 = pd.Series([10,20,30,40])
series1

0    10
1    20
2    30
3    40
dtype: int64

In [30]:
series1.values

array([10, 20, 30, 40], dtype=int64)

In [32]:
series1.index

RangeIndex(start=0, stop=4, step=1)

In [34]:
series2 = pd.Series([10,20,30,40,50], index=[1,2,3,4,5])
series2

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [36]:
series2[6]

KeyError: 6

In [38]:
series2['three']
series2[['one','three','five']]
series2[[0,1,3]]

KeyError: 'three'

In [39]:
series2[[0,1,3]]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:942: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


0     NaN
1    10.0
3    30.0
dtype: float64

In [40]:
series2 + 4

1    14
2    24
3    34
4    44
5    54
dtype: int64

In [41]:
series2 **3

1      1000
2      8000
3     27000
4     64000
5    125000
dtype: int64

In [42]:
series2[series2>30]

4    40
5    50
dtype: int64

In [43]:
np.sqrt(series2)

1    3.162278
2    4.472136
3    5.477226
4    6.324555
5    7.071068
dtype: float64

In [44]:
years = [91, 90, 92, 93, 94, 95, 95, 97]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11, 96:13}
firm1 = pd.Series(f1,index=years)
firm1

91     9.0
90     8.0
92     7.0
93     8.0
94     9.0
95    11.0
95    11.0
97     NaN
dtype: float64

In [45]:
f2 = {90:14, 92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
firm2

91     NaN
90    14.0
92     9.0
93    13.0
94     5.0
95     NaN
95     NaN
97     NaN
dtype: float64

In [46]:
pd.isnull(firm2)

91     True
90    False
92    False
93    False
94    False
95     True
95     True
97     True
dtype: bool

In [50]:
dict1 = {'finance': 10, 'earning': 5, 'debt':8}
dict2 = {'finance' : 8, 'compensation':4, 'earning': 9}
count1 = pd.Series(dict1)
count2 = pd.Series(dict2)
print (count1)
print (count2)

finance    10
earning     5
debt        8
dtype: int64
finance         8
compensation    4
earning         9
dtype: int64


In [51]:
count1+count2

compensation     NaN
debt             NaN
earning         14.0
finance         18.0
dtype: float64

In [57]:
data = pd.DataFrame({'price':[95, 25, 41, 78],
                     'ticker':['AXP', 'CSCO', 'DIS', 'MSFT', 'WMT'],
                     'company':['American Express', 'Cisco', 'Walt Disney','Microsoft', 'Walmart']})
data

ValueError: arrays must all be same length

In [58]:
data = pd.DataFrame({'price':[95, 25, 85, 41, 78],
                     'ticker':['AXP', 'CSCO', 'DIS', 'MSFT', 'WMT'],
                     'company':['American Express', 'Cisco', 'Walt Disney','Microsoft', 'Walmart']})
data

price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   MSFT         Microsoft
4     78    WMT           Walmart

In [59]:
data['company']

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [60]:
data.company

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [61]:
print (data.ix[2])

price               85
ticker             DIS
company    Walt Disney
Name: 2, dtype: object


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [62]:
data.ix[data.ticker=='DIS']

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


price ticker      company
2     85    DIS  Walt Disney

In [63]:
data['Year'] = 2014
data

price ticker           company  Year
0     95    AXP  American Express  2014
1     25   CSCO             Cisco  2014
2     85    DIS       Walt Disney  2014
3     41   MSFT         Microsoft  2014
4     78    WMT           Walmart  2014

In [64]:
data['pricesquared'] = data.price**2
data

price ticker           company  Year  pricesquared
0     95    AXP  American Express  2014          9025
1     25   CSCO             Cisco  2014           625
2     85    DIS       Walt Disney  2014          7225
3     41   MSFT         Microsoft  2014          1681
4     78    WMT           Walmart  2014          6084

In [65]:
del data['pricesquared']
data

price ticker           company  Year
0     95    AXP  American Express  2014
1     25   CSCO             Cisco  2014
2     85    DIS       Walt Disney  2014
3     41   MSFT         Microsoft  2014
4     78    WMT           Walmart  2014

In [ ]:
data['pricesquared'] = np.NaN
