In [1]:
def func_python(N):
    d=0
    for i in range(N):
        d +=(i %3 - 1)*i
        return d

In [3]:
%timeit func_python(10000)

2.91 µs ± 609 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
def func_python(N):
    d=0
    for i in range(N):
        d += (i % 3 -1) * i
        return d

In [5]:
%timeit func_python(10000)

1.9 µs ± 27.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
def func_python(N):
    d=0
    for i in range(N):
        d += (i %3 - 1) * i
        return d

In [7]:
%timeit func_python(10000)

The slowest run took 6.03 times longer than the fastest. This could mean that an intermediate result is being cached.
6.21 µs ± 4.48 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
distance = [45,50,35]
speed = [5,10,7]


time = distance/speed
print (time)


TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [9]:
import numpy as np

In [10]:
from numpy import array
from numpy import arange

In [11]:
dist = array(distance)
spd = np. array(speed)
print (dist)
print (spd)
time= dist/spd
print (time)
len(time)

[45 50 35]
[ 5 10  7]
[9. 5. 5.]


3

In [12]:
dist = array(distance)
spd = np.array(speed)
print (dist)
print (spd)
time= dist/spd
print (time)
len(time)

[45 50 35]
[ 5 10  7]
[9. 5. 5.]


3

In [13]:
a=[1,2,3,4,5]
b=[10,20,30,40]
print (a +b)
c = [val + 5 for val in a]
print (c)

[1, 2, 3, 4, 5, 10, 20, 30, 40]
[6, 7, 8, 9, 10]


In [14]:
f = array((1,2,3,4,5))
g = array((10,20,30,40))
print(a)
print(b)
print(f+g)
print(f+5)
f**2
g**3

[1, 2, 3, 4, 5]
[10, 20, 30, 40]


ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [16]:
c = array(arange(10))
print ('array:                       ',c)
print()
print()
       
anarray = array(np.arange(5,56,5))
print ('anarray:                    ',anarray)
print ()
print()
       
       
onemorearray = array(np.linspace(3,4,13))
print ('onemorearray:                  ', onemorearray)
print ('Rounded onemorearray:       ', np.round(onemorearray,0))
onemorearray.sum()       

array:                        [0 1 2 3 4 5 6 7 8 9]


anarray:                     [ 5 10 15 20 25 30 35 40 45 50 55]


onemorearray:                   [3.         3.08333333 3.16666667 3.25       3.33333333 3.41666667
 3.5        3.58333333 3.66666667 3.75       3.83333333 3.91666667
 4.        ]
Rounded onemorearray:        [3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4.]


45.5

In [18]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,5))   +  6

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [20]:
np.zeros((3,5))  +  6

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [21]:
np.ones(30)   + 7

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [22]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [24]:
np.diag(array([1,3,5,3,4,5]))

array([[1, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

In [25]:
import pandas as pd
import numpy as np


In [26]:
series1 = pd. Series([10,20,30,40])
series1

0    10
1    20
2    30
3    40
dtype: int64

In [27]:
series1.values

array([10, 20, 30, 40], dtype=int64)

In [28]:
series1.index

RangeIndex(start=0, stop=4, step=1)

In [29]:
series2 = pd.Series([10,20,30,40,50], index=[1,2,3,4,5])
series2

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [30]:
series2[6]

KeyError: 6

In [32]:
series2['three']

KeyError: 'three'

In [33]:
series2[['one', 'three', 'five']]

KeyError: "None of [Index(['one', 'three', 'five'], dtype='object')] are in the [index]"

In [34]:
series2[[0,1,3]]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:942: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


0     NaN
1    10.0
3    30.0
dtype: float64

In [35]:
series2 + 4

1    14
2    24
3    34
4    44
5    54
dtype: int64

In [36]:
series2 ** 3

1      1000
2      8000
3     27000
4     64000
5    125000
dtype: int64

In [37]:
np.sqrt(series2)

1    3.162278
2    4.472136
3    5.477226
4    6.324555
5    7.071068
dtype: float64

In [1]:
years

NameError: name 'years' is not defined

In [3]:
your_local _path='C:/Users/Syed Nizam/Downloads'

SyntaxError: invalid syntax (<ipython-input-3-3ff43bd5d2d3>, line 1)

In [4]:
def func_python(N):
    d=0
    for i in range(N):
        d +=(i % 3 - 1) * i
        return d

In [6]:
%timeit func_python(10000)

1.91 µs ± 332 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
distance = [45,50,35]
speed = [5,10,7]


time = distance/speed
print(time)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [9]:
import numpy as np


In [10]:
from numpy import array
from numpy import arange

In [12]:
dist = array(distance)
spd = np.array(speed)
print(list)
print(spd)
time=dist/spd
print (time)
len(time)

<class 'list'>
[ 5 10  7]
[9. 5. 5.]


3

In [13]:
dist = array(distance)
spd = np.array(speed)
print(dist)
print(spd)
time= dist/spd
print (time)
len(time)

[45 50 35]
[ 5 10  7]
[9. 5. 5.]


3

In [16]:
dist = array(distance)
spd = np.array(speed)
print(dist)
print(spd)
time= dist/spd
print(time)
len(time)

[45 50 35]
[ 5 10  7]
[9. 5. 5.]


3

In [17]:
a=[1,2,3,4,5]
b=[10,20,30,40]
print (a + b)
print (a + 5)
c = [val + 5 for val in a]
print(c)

[1, 2, 3, 4, 5, 10, 20, 30, 40]


TypeError: can only concatenate list (not "int") to list

In [18]:
f = array((1,2,3,4,5))
g = array((10,20,30,40))
print(a)
print(b)
print(f+g)
print(f+5)
f**2
g**3

[1, 2, 3, 4, 5]
[10, 20, 30, 40]


ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [20]:
c = array(arange(10))
print ('array:               ', c)
print()
print()



anarray = array(np.arange(5,56,5))
print ('anarray:                ',anarray)
print()
print()

onemorearray = array(np.linspace(3,4,13))
print ('onemorearray:              ', onemorearray)
print ('Rounded onemorearray: ', np.round(onemorearray,0))
onemorearray.sum()

array:                [0 1 2 3 4 5 6 7 8 9]


anarray:                 [ 5 10 15 20 25 30 35 40 45 50 55]


onemorearray:               [3.         3.08333333 3.16666667 3.25       3.33333333 3.41666667
 3.5        3.58333333 3.66666667 3.75       3.83333333 3.91666667
 4.        ]
Rounded onemorearray:  [3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4.]


45.5

In [22]:
c = array(arange(10))
print ('array:                 ', c)
print()
print()




anarray = array(np.arange(5,56,5))
print ('anarray:                ',anarray)
print()
print()


onemorearrayh = array(np.linspace(3,4,13))
print ('onemorearray:           ',onemorearray)
print ('Rounded onemorearray:     ',np.round(onemorearray,0))
onemorearray.sum()

array:                  [0 1 2 3 4 5 6 7 8 9]


anarray:                 [ 5 10 15 20 25 30 35 40 45 50 55]


onemorearray:            [3.         3.08333333 3.16666667 3.25       3.33333333 3.41666667
 3.5        3.58333333 3.66666667 3.75       3.83333333 3.91666667
 4.        ]
Rounded onemorearray:      [3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4.]


45.5

In [24]:
data = np.array((32,45,756,23,2123,1,2,3,4,,5,6,6,5,4,3,2,1,78,89,87,76,54,31))
data2 = data.reshape(2,2.2,3)
print(data)
print ("*****")
print (data2)
print( data2.shape)
print (data2.dtype)
print(data2.size)
print (data2.size)
even_data = (data % 2 = 0)
print (even_data)
data[even_data]

SyntaxError: invalid syntax (<ipython-input-24-42e46b08f2ba>, line 1)

In [2]:
ans=(lambda z:z*4)
print(ans(7))

28


In [3]:
ans=(lambda z:z*4)
print(ans(7))

28


In [4]:
def print_name(str):
    we
    =("Welcome to Python, "str)
    return(wel)
str=input("Enter your name")
Out=print_name(str)
print(Out)

SyntaxError: invalid syntax (<ipython-input-4-1f9d675c6d0e>, line 2)

In [6]:
ans=(lambda z:z*4)
print(ans(7))

28


In [7]:
ans=(lambda z:z*4)
print(ans(4))

16


In [8]:
ans=(lambda z:z*8)
print(ans(8))

64


In [10]:
ans=(lambda y:y*5)
print(ans(5))

25


In [12]:
items = [1, 2, 3, 4, 5]
squared = list(map(lambda x:x**2, items))
print(squared)

[1, 4, 9, 16, 25]


In [13]:
items = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x**2, items))
print(squared)

[1, 4, 9, 16, 25]


In [16]:
number_list = range(-5, 5)
less_than_zero = list(filter(lambda x: x <0, number_list))
print(less_than_zero)

[-5, -4, -3, -2, -1]


In [17]:
from functools import reduce
product = reduce((lambda x, y: x* y), [1, 2, 3,4])
print(product)

24


In [21]:
from functools import reduce
product = reduce((lambda x, y: x * y), [1, 2, 3, 4])


print(product)

24


In [22]:
from functools import reduce
product = reduce((lambda x, y: x * y), [1, 2, 3, 4])
print(product)

24


In [23]:
from functools import reduce
product = reduce((lambda x, y: x * y), [1, 2, 3, 4])
print(product)

24


In [28]:
from functools import reduce

product = reduce((lambda x, y: x * y), [1, 2, 3, 4])
print(product)

24


In [31]:
from functools import reduce
product = reduce((lambda x, y: x * y), [1, 2, 3, 4])
print(product)

24


In [32]:
a=50
def  number():
    b=30
    print(b)
    
print(a)
number()
         

50
30


In [33]:
a=50
def number():
    b=30
    print(b)
print(a) 
number()

50
30


In [36]:
a=50
def number():
    b=30
    print(b)
print(a)
number()

50
30


In [37]:
a=50
def umber():
    b=30
    print(b)
    
print(a)
number()

50
30


In [38]:
a=50
def number()
    b=30
    print(b)
    
    
print(a)
number()

SyntaxError: invalid syntax (<ipython-input-38-e7dd4cd342ae>, line 2)

In [40]:
a=50
def number() :
    b=30
    print(b)
    
print(a)
number()

50
30


In [44]:
a=30
def add(b):
    c=30
    print("c=",c)
    sum=b+c
    print("Addition is: ",sum)
    
    print(a)
    add(40)
    print(c)

In [45]:
a=30
def add(b):
    c=30
    print("c",c)
    sum=b+c
    print("Addition is: ",sum)
    
print(a)
print(40)
print(c)


30
40


NameError: name 'c' is not defined

In [1]:
a=10
b=10

print(id(a))
print(id(b))

140731088409696
140731088409696


In [2]:
a=10
b=10

print(id(a))
print(id(b))

140731088409696
140731088409696


In [5]:
def print_name(Str):
    print("welcome to Python, ",str)
                      return()
print_name()      

IndentationError: unexpected indent (<ipython-input-5-73a12048f7db>, line 3)

In [6]:
def  Welcome(str):
    print("Welcome to Python,",str)
    return()
Welcome(str="Annie")

Welcome to Python, Annie


()

In [7]:
def Welcome(str):
    print("Welcome to Python, ",str)
    return()
Welcome(str="Annie")

Welcome to Python,  Annie


()

In [9]:
def Welcome(str):
    print("Welcome to Python,",str)
    return()
Welcome(str="Annie")

Welcome to Python, Annie


()

In [10]:
def Welcome(str):
    print("Welcome  to Python,",str)
    return()
Welcome(str="Annie")

Welcome  to Python, Annie


()

In [11]:
def Welcome(str):
    print("Welcome to Python,",str)
    return()
Welcome(str="Annie")

Welcome to Python, Annie


()

In [12]:
def Welcome(str):
    print("Welcome to Python,",str)
    return()
Welcome(str="Annie")

Welcome to Python, Annie


()

In [13]:
def Welcome(str):
    print("Welcome to Python,",str)
    return()
Welcome(str="Annie")

Welcome to Python, Annie


()

In [14]:
def Welcome(str):
    print("Welcome to Python,",str)
    return()
Welcome(str="Annie")

Welcome to Python, Annie


()

In [15]:
def Welcome(str):
    print("Welcome to Python,",str)
    return()
Welcome(str="Annie")

Welcome to Python, Annie


()

In [16]:
def Welcome(str):
    print("Welcome to Python,",str)
    return()
Welcome(str="Annie")

Welcome to Python, Annie


()

In [17]:
def add(a,b,c,d):
    print(a)
    print(b)
    print(c)
    print(d)
    sum=a+b+c+d
    return(sum)

ans=add(d=10,a=50,c=5,b=5)
print("Sum is :",ans)
    

50
5
5
10
Sum is : 70


In [18]:
def add(a,b,c,d):
    print(a)
    print(b)
    print(c)
    print(d)
    sum=a+b+c+d
    return(sum)

ans=add(d=10,a=50,c=5,b=5)
print("Sum is : ",ans)

50
5
5
10
Sum is :  70


In [19]:
def info(name,age=50):
    print("Name: ",name)
    print("Age :",age)
    return()

info(age=25, name="Annie")
info(name="Miki")

Name:  Annie
Age : 25
Name:  Miki
Age : 50


()

In [20]:
def info(name,age=50):
    print("Name: ",name)
    print("Age :",age)
    return()
info(age=25,name="Annie")
info(name="Miki")

Name:  Annie
Age : 25
Name:  Miki
Age : 50


()

In [21]:
def info(name,age=50):
    print("Name: ",name)
    print("Age :",age)
    return()
info(age=25,name="Annie")
info(name="Miki")

Name:  Annie
Age : 25
Name:  Miki
Age : 50


()

In [22]:
def info(name, age=50) :
    print("Name: ",name)
    print("Age  :",age)
    return()

info(age=25,name="Annie")
info(name="Miki")

Name:  Annie
Age  : 25
Name:  Miki
Age  : 50


()

In [23]:
def info(name,age=50):
    print("Name: ",name)
    print("Age :",age)
    return()

info(age=25,name="Annie")
info(name="Miki")

Name:  Annie
Age : 25
Name:  Miki
Age : 50


()

In [24]:
def info(name,age=50):
    print("Name: ",name)
    print("Age :",age)
    return()

info(age=25,name="Annie")
info(name="Miki")

Name:  Annie
Age : 25
Name:  Miki
Age : 50


()

In [26]:
def info(name,age=50):
    print("Name: ",name)
    print("Age :",age)
    return()

info(age=25, name="Annie")
info(name="Miki")

Name:  Annie
Age : 25
Name:  Miki
Age : 50


()

In [27]:
def employee(name,id,salary=10000):
    print("Name of Employee: ",name)
    print("ID no of Employee: ",id)
    print("Salary of Employe: ",salary)
employee("Sara",101,20000)
employee("Alex",98)

Name of Employee:  Sara
ID no of Employee:  101
Salary of Employe:  20000
Name of Employee:  Alex
ID no of Employee:  98
Salary of Employe:  10000


In [28]:
def employee(name,id,salary=10000):
    print("Name of Employee: ",name)
    print("ID no of Employee: ",id)
    print("Salary of  Employe: ",salary)
    
employee("Sara",101,20000)
employee("Alex",98)

Name of Employee:  Sara
ID no of Employee:  101
Salary of  Employe:  20000
Name of Employee:  Alex
ID no of Employee:  98
Salary of  Employe:  10000


In [30]:
def info(user,*users):
    print("Users of Python:")
    print(user)
    for Var in users:
        print("Users of Python")
        print(Var)
        return()
info("Annie")
info("Annie","Dave")

Users of Python:
Annie
Users of Python:
Annie
Users of Python
Dave


()

In [31]:
class number():
    pass
x=number()
print(x)

In [35]:
class number():
    pass
x=number()
print((x))

In [36]:
class number():
        pass
x=number()
print(x)

In [37]:
class number():
    pass
x=number()
print(x)

In [38]:
class number():
    pass
x=number()
print(x)

In [39]:
class number():
    pass
x=number()
pirnt(x)

NameError: name 'pirnt' is not defined

In [ ]:
def add(a,b):
    sum=a+b
    return (sum)

num1=input("Enter first number")
num2=input("Enter second number")
n1=int(num1)
n2=int(num2)
ans=add(n1,n2)
print("Addition of 2 number is:",ans)


In [4]:
ans=(lambda y:y*7)
print(ans(4))

28


In [ ]:
print(hello)

In [1]:
print(hello)

NameError: name 'hello' is not defined

In [3]:
a=("hello")
print(a)

hello


In [5]:
ans=(lambda y:y*5)
print(ans(9))

45


In [6]:
a=50
def number():
    b=30
    print(b)
print(a)
number()

50
30


In [7]:
a=50
def number():
    b=30
    print(b)

print(a)
number()

50
30


In [9]:
def Welcome(str):
    print("Welcome to Python, ",str)
    return()
Welcome(str="Annie")

Welcome to Python,  Annie


()

In [10]:
def Welcome(str):
    print("Welcome to Python,",str)
    return()
Welcome(str="Annie")

Welcome to Python, Annie


()

In [11]:
def info(name,age=50):
    print("Name: ",name)
    print("Age :",age)
    return()


info(age=25,name='Annie')
info(name="Miki")

Name:  Annie
Age : 25
Name:  Miki
Age : 50


()

In [1]:
class number():
    pass
x=number()
print(x)

In [3]:
class number():
    pass
x=number()
print(x)

In [6]:
class Edureka():
    def Hello(self):
        print("Happy Learning")
ob=Edureka()
ob.Hello()

Happy Learning


In [5]:
class Edureka():
    def Hello(self):
        print("Happy Learning")
ob=Edureka()
ob.Hello()

Happy Learning


In [8]:
class Edureka():
    def Hello(self):
        print("Happy Learning")
ob=Edureka()
ob.Hello()

Happy Learning


In [9]:
class Edureka():
    def Hello(self):
        print("Happy Learning")
ob=Edureka() 
ob.Hello()
            

Happy Learning


In [10]:
print("Happy Learning")

Happy Learning


In [12]:
a=50
class Edureka():
    b=60
    print(b)
ob=Edureka()    

60


In [13]:
a=50
class Edureka():
    b=60
    print(b)
ob=Edureka()    

60


In [14]:
a=50
class Edureka():
    b=60
    print(b)
ob=Edureka()    

60


In [15]:
class Edureka:
    empcount=0
    
print("Edureka.__dict__:",Edureka.__dict__)    

Edureka.__dict__: {'__module__': '__main__', 'empcount': 0, '__dict__': <attribute '__dict__' of 'Edureka' objects>, '__weakref__': <attribute '__weakref__' of 'Edureka' objects>, '__doc__': None}


In [16]:
print("Edureka.__doc__:",Edureka.__doc__)

Edureka.__doc__: None


In [18]:
print("Edureka.__name__",Edureka.__name__)

Edureka.__name__ Edureka


In [20]:
print("Edureka.__module__:",Edureka.__module__)

Edureka.__module__: __main__


In [21]:
print("Edureka.__bases__:",Edureka.__bases__)

Edureka.__bases__: (<class 'object'>,)


In [23]:
class Hsbc:
    empcount=0
print("Hsbc.__dict__:",Hsbc.__dict__)    

Hsbc.__dict__: {'__module__': '__main__', 'empcount': 0, '__dict__': <attribute '__dict__' of 'Hsbc' objects>, '__weakref__': <attribute '__weakref__' of 'Hsbc' objects>, '__doc__': None}


In [25]:
print("Hsbc.__doc__:",Hsbc.__doc__)

Hsbc.__doc__: None


In [26]:
print("Hsbc.__name__",Hsbc.__name__)

Hsbc.__name__ Hsbc


In [27]:
print("Hsbc.__module__",Hsbc.__module__)

Hsbc.__module__ __main__


In [28]:
print("Hsbc.__bases__",Hsbc.__bases__)

Hsbc.__bases__ (<class 'object'>,)


In [29]:
class Foo(object):
    def math(self):
        pass

In [31]:
class Microsoft:
    empcount=0
print("Microsoft.__dict__",Microsoft.__dict__)    

Microsoft.__dict__ {'__module__': '__main__', 'empcount': 0, '__dict__': <attribute '__dict__' of 'Microsoft' objects>, '__weakref__': <attribute '__weakref__' of 'Microsoft' objects>, '__doc__': None}


In [32]:
print("Microsoft.__doct",Microsoft.__doc__)

Microsoft.__doct None


In [35]:
print("Microsoft.__name__",Microsoft.__name__)

Microsoft.__name__ Microsoft


In [39]:
print("Mcirosoft.__module__",Microsoft.__module__)

Mcirosoft.__module__ __main__


In [42]:
print("Microsoft.__bases__",Microsoft.__bases__)

Microsoft.__bases__ (<class 'object'>,)


In [43]:
class Foo(object):
    def math(self):
        pass

In [54]:
class Edureka():
    def __init__(self):
        self.__pri=("I am Private")
        self._pro=("I am Protected")
        self.pub=("I am Public")
        
ob=Edureka()
print(ob.pub)
print(ob._pro)
print(ob.__pri)

I am Public
I am Protected


AttributeError: 'Edureka' object has no attribute '__pri'

In [57]:
class MyClass:
    def myPublicMethod(self):
        print('public method')
    def __myPrivateMethod(self):
        print('this is Private!!')
obj = MyClass()
obj.myPublicMethod()

obj.__myPrivateMethod()

public method


AttributeError: 'MyClass' object has no attribute '__myPrivateMethod'

In [59]:
class MyClass:
    def myPublicMethod(self):
        print('Pubic method')
    def __myPrivateMethod(self):
        print('this is private!!')

obj = MyClass()
obj.myPublicMethod()

obj.__myPrivateMethod()

Pubic method


AttributeError: 'MyClass' object has no attribute '__myPrivateMethod'

In [60]:
class MyClass:
    def myPublicMethod(self):
        print('public method')
    def __myPrivateMethod(self):
        print('this is Private!!')
obj = MyClass()
obj.myPublicMethod()

obj._MyClass__myPrivateMethod()


public method
this is Private!!


In [61]:
class MyClass:
    def myPublicMethod(self):
        print('public method')
    def __myPrivateMethod(self):
        print('this is private!!')
obj = MyClass()
obj.myPublicMethod()

obj._MyClass__myPrivateMethod()

public method
this is private!!


In [63]:
class MyClass:
    def myPublicMethod(self):
        print('public method')
    def __myPrivateMethod(self):
        print('this is private!!')
        
obj = MyClass()
obj.myPublicMethod()

obj._MyClass__myPrivateMethod()

public method
this is private!!


In [2]:
import numpy as np

a = np.array([1, 2, 3])
print(a)
    

[1 2 3]


In [5]:
a = np.array([[1, 2], [2, 4]])
print(a)

[[1 2]
 [2 4]]


In [6]:
a = np.array([[1, 2],[8, 8]])
print(a)

[[1 2]
 [8 8]]


In [7]:
list1 = [1, 2, 3, 4, 5]
arr = np.array(list1)
print(list1)

[1, 2, 3, 4, 5]


In [8]:
list2 = [7, 8, 9, 10, 11]
arr = np.array(list2)
print(list2)

[7, 8, 9, 10, 11]


In [9]:
arr = np.arange(10, 100)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [10]:
arr = np.arange(10 ,100)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [11]:
arr = np.arange(1, 99)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98]


In [12]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
arr = np.zeros((10,10))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
arr = np.zeros((15, 15))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
vector = np.linspace(0, 20, 5)
print(vector)

[ 0.  5. 10. 15. 20.]


In [18]:
vector = np.linspace(0, 20, 5)
print(vector)

[ 0.  5. 10. 15. 20.]


In [19]:
vector = np.linspace(0, 25, 5)
print(vector)

[ 0.    6.25 12.5  18.75 25.  ]


In [20]:
x=[1,2,3]
a=np.asarray(x)
print(a)

[1 2 3]


In [21]:
x=[5,6,7]
a=np.asarray(x)
print(a)

[5 6 7]


In [22]:
x=[7,8,9]
c=np.asarray(x)
print(c)

[7 8 9]


In [24]:
arr=np.zeros(8)
arr3d=arr.reshape((2,2,2))
print(arr3d)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [26]:
arr=np.zeros(8)
arr3d=arr.reshape((2,2,2))
print(arr3d)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [28]:
arr=np.zeros(8)
arr3d=arr.reshape((2,2,2))
arr=arr3d.ravel()
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
arr=np.zeros(8)
arr3d=arr.reshape((2,2,2))
arr=arr3d.ravel()
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
arr=np.zeros(8)
arr3d=arr.reshape((2,2,2))
arr=arr3d.ravel()
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
arr=np.zeros(8)
arr3d=arr.reshape((2,2,2))
arr=arr3d.ravel()
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [35]:
arr=np.arange(2,20)
element=arr[6]
(element)

8


In [36]:
import numpy as np
arr=np.arange(2,20)
element=arr[6]
print(element)

8


In [37]:
import numpy as np
arr=np.arange(2,20)
element=arr[6]
print(element)

8


In [38]:
import numpy as np
arr=np.arange(2,20)
element=arr[6]
print(element)

8


In [39]:
arr=np.arange(2,25)
element=arr[6]
print(element)

8


In [41]:
arr=np.arange(3,25)
element=arr[5]
print(element)

8


In [42]:
arr=np.arange(4,16)
element=arr[4]
print(element)

8


In [43]:
arr=np.arange(20)
arr_slice=slice(1,10,2)
element=arr[6]
print(arr[arr_slice])

[1 3 5 7 9]


In [44]:
arr=np.arange(20)
arr_sliced=slice(1,10,2)
element=arr[6]
print(arr[arr_slice])

[1 3 5 7 9]


In [45]:
arr=np.arange(20)
arr_slice=slice(1,10,2)
element=arr[6]
print(arr[arr_slice])

[1 3 5 7 9]


In [46]:
arr=np.arange(20)
arr_slice=slice(1,10,2)
element=arr[6]
print(arr[arr_slice])

[1 3 5 7 9]


In [47]:
arr=np.arange(20)
arr_slice=slice(1,10,5)
element=arr[6]
print(arr[arr_slice])

[1 6]


In [48]:
arr=np.arange(20)
arr_slice=slice(1,10,4)
element=arr[6]
print(arr[arr_slice])

[1 5 9]


In [49]:
arr=np.arange(40)
arr_slice=slice(1,10,9)
element=arr[6]
print(arr[arr_slice])

[1]


In [51]:
arr=np.arange(20)
arr_slice=slice(1,10,5)
element=arr[6]
print(arr[arr_slice])

[1 6]


In [52]:
arr=np.arange(20)
print(arr[2:])

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [53]:
arr=np.arange(20)
print(arr[:2])

[0 1]


In [54]:
arr=np.arange(30)
print(arr[3:])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29]
